apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-producer
  template:
    metadata:
      labels:
        app: data-producer
    spec:
      containers:
        - name: data-producer
          image: digital-twin/data-producer:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: digital-twin-config
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: digital-twin-config
                  key: KAFKA_CLIENT_ID_PRODUCER
